import type { CardDef, EnemyTemplate, EventDef, NodeType, RelicDef } from "./types";

export const CARD_DEFS: Record<string, CardDef> = {
  strike: {
    id: "strike",
    name: "清網行動",
    type: "attack",
    rarity: "basic",
    cost: 1,
    text: ["造成 6 點傷害。", "造成 9 點傷害。"],
  },
  defend: {
    id: "defend",
    name: "防護浮具",
    type: "skill",
    rarity: "basic",
    cost: 1,
    text: ["獲得 5 點防護。", "獲得 8 點防護。"],
  },
  zhusha: {
    id: "zhusha",
    name: "污染標記",
    type: "attack",
    rarity: "basic",
    cost: 1,
    text: ["造成 4 點傷害。施加 1 層污染指數。", "造成 6 點傷害。施加 2 層污染指數。"],
  },
  taomu: {
    id: "taomu",
    name: "快艇衝撞",
    type: "attack",
    rarity: "common",
    cost: 1,
    text: ["造成 4 點傷害 2 次。", "造成 5 點傷害 2 次。"],
  },
  cloudstep: {
    id: "cloudstep",
    name: "潮流借力",
    type: "skill",
    rarity: "common",
    cost: 0,
    text: ["獲得 3 點防護。抽 1 張牌。", "獲得 5 點防護。抽 1 張牌。"],
  },
  qingxin: {
    id: "qingxin",
    name: "深呼吸",
    type: "skill",
    rarity: "common",
    cost: 0,
    text: ["抽 2 張牌。", "抽 3 張牌。"],
  },
  golden: {
    id: "golden",
    name: "防護網",
    type: "skill",
    rarity: "common",
    cost: 1,
    text: ["獲得 8 點防護與 1 點潮力。", "獲得 11 點防護與 1 點潮力。"],
  },
  incense: {
    id: "incense",
    name: "蓄潮",
    type: "skill",
    rarity: "common",
    cost: 0,
    exhaust: true,
    text: ["獲得 2 點潮力。消耗。", "獲得 3 點潮力。消耗。"],
  },
  windScroll: {
    id: "windScroll",
    name: "洋流感知",
    type: "skill",
    rarity: "common",
    cost: 0,
    text: ["抽 1 張牌。若敵人有污染指數，額外抽 1 張。", "抽 1 張牌。若敵人有污染指數，額外抽 2 張。"],
  },
  thunder: {
    id: "thunder",
    name: "聲納衝擊",
    type: "attack",
    rarity: "common",
    cost: 2,
    text: ["造成 10 點傷害。若敵人有污染指數，額外造成 6 點傷害。", "造成 14 點傷害。若敵人有污染指數，額外造成 8 點傷害。"],
  },
  bell: {
    id: "bell",
    name: "纏繞浮繩",
    type: "skill",
    rarity: "common",
    cost: 1,
    text: ["獲得 3 點防護。施加 2 層虛弱。", "獲得 5 點防護。施加 3 層虛弱。"],
  },
  fog: {
    id: "fog",
    name: "水下視野",
    type: "skill",
    rarity: "common",
    cost: 1,
    text: ["獲得 6 點防護。抽 1 張牌。", "獲得 9 點防護。抽 1 張牌。"],
  },
  command: {
    id: "command",
    name: "緊急通報",
    type: "skill",
    rarity: "uncommon",
    cost: 2,
    text: ["獲得 4 點防護。施加 4 層污染指數。", "獲得 6 點防護。施加 5 層污染指數。"],
  },
  burn: {
    id: "burn",
    name: "污染爆發",
    type: "attack",
    rarity: "uncommon",
    cost: 1,
    text: ["移除所有污染指數。每層造成 5 點傷害。", "移除所有污染指數。每層造成 7 點傷害。"],
  },
  paper: {
    id: "paper",
    name: "誘餌浮標",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    text: ["獲得 7 點防護。將 1 張魚叉加入手牌。", "獲得 10 點防護。將 1 張強化魚叉加入手牌。"],
  },
  breakEvil: {
    id: "breakEvil",
    name: "執法扣押",
    type: "attack",
    rarity: "uncommon",
    cost: 2,
    text: ["造成 14 點傷害。若敵人有污染指數，獲得 1 點能量。", "造成 18 點傷害。若敵人有污染指數，獲得 1 點能量。"],
  },
  mirror: {
    id: "mirror",
    name: "衛星標記",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    text: ["施加 2 層污染指數與 2 層易傷。", "施加 3 層污染指數與 2 層易傷。"],
  },
  refine: {
    id: "refine",
    name: "屏息潛水",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    exhaust: true,
    text: ["獲得 1 點能量。失去 2 點生命。消耗。", "獲得 1 點能量。失去 1 點生命。消耗。"],
  },
  scripture: {
    id: "scripture",
    name: "調閱資料",
    type: "skill",
    rarity: "uncommon",
    cost: 1,
    text: ["抽 3 張牌，將 1 張污泥加入棄牌堆。", "抽 4 張牌，將 1 張污泥加入棄牌堆。"],
  },
  ashReturn: {
    id: "ashReturn",
    name: "潮汐回流",
    type: "skill",
    rarity: "uncommon",
    cost: 0,
    text: ["將棄牌堆洗回抽牌堆。抽 1 張牌。獲得 4 點防護。", "將棄牌堆洗回抽牌堆。抽 2 張牌。獲得 6 點防護。"],
  },
  nightEye: {
    id: "nightEye",
    name: "生態監測儀",
    type: "power",
    rarity: "rare",
    cost: 1,
    text: ["法門：每回合多抽 1 張牌。", "法門：每回合多抽 1 張牌。立即抽 1 張牌。"],
  },
  citygod: {
    id: "citygod",
    name: "呼叫中心支援",
    type: "power",
    rarity: "rare",
    cost: 2,
    text: ["法門：每回合獲得 3 點防護與 1 點潮力。", "法門：每回合獲得 5 點防護與 1 點潮力。"],
  },
  thunderLaw: {
    id: "thunderLaw",
    name: "全力清污",
    type: "attack",
    rarity: "rare",
    cost: 3,
    text: ["消耗所有潮力。造成 12 點傷害，每點潮力額外 +5。", "消耗所有潮力。造成 16 點傷害，每點潮力額外 +6。"],
  },
  paperBlade: {
    id: "paperBlade",
    name: "魚叉",
    type: "attack",
    rarity: "special",
    cost: 0,
    exhaust: true,
    text: ["造成 3 點傷害。消耗。", "造成 5 點傷害。消耗。"],
  },
  yinCold: {
    id: "yinCold",
    name: "污泥",
    type: "status",
    rarity: "status",
    cost: "-",
    unplayable: true,
    text: ["無法打出。回合結束時若在手牌，失去 2 點生命。", "無法打出。回合結束時若在手牌，失去 2 點生命。"],
  },
};

export const CARD_POOL = Object.keys(CARD_DEFS).filter((id) => {
  const rarity = CARD_DEFS[id].rarity;
  return !["basic", "special", "status"].includes(rarity);
});

export const RELICS: RelicDef[] = [
  { id: "bronzeMirror", name: "舊式聲納儀", text: "每場戰鬥開始時，施加 2 層污染指數。" },
  { id: "taomuTassel", name: "破網剪刀", text: "每場戰鬥第一張攻擊牌額外造成 4 點傷害。" },
  { id: "citySeal", name: "海洋教育中心識別章", text: "每場戰鬥第一回合獲得 2 點潮力。" },
  { id: "brokenCenser", name: "舊氧氣筒", text: "每打出一張技能牌，獲得 1 點防護。" },
  { id: "nightSand", name: "生物發光樣本", text: "每場戰鬥第一回合多抽 1 張牌。" },
  { id: "oldUmbrella", name: "防水夾克", text: "每場戰鬥第一回合獲得 6 點防護。" },
  { id: "thunderWood", name: "電鰻標本", text: "污染指數每層傷害提高 1。" },
  { id: "blankPage", name: "布袋海域調查筆記", text: "每回合每打出 3 張牌，抽 1 張牌。" },
  { id: "paperHorse", name: "迷你無人機", text: "每場戰鬥第一回合獲得 1 點額外能量。" },
  { id: "foxCoin", name: "漁港舊錢幣", text: "獲得時立即得到 60 金。", onGain: "gold60" },
];

export const ENEMIES: Record<string, EnemyTemplate> = {
  lantern: {
    id: "lantern",
    name: "飄流垃圾堆",
    artKey: "lantern",
    hp: 42,
    moves: [
      { type: "attack", amount: 6, label: "纏繞衝擊" },
      { type: "curse", amount: 1, label: "污染滲透" },
      { type: "block", amount: 7, label: "垃圾堆積" },
    ],
  },
  waterghost: {
    id: "waterghost",
    name: "廢棄漁網",
    artKey: "waterghost",
    hp: 48,
    moves: [
      { type: "attack", amount: 8, label: "網線纏身" },
      { type: "debuff", amount: 2, label: "深海困縛" },
      { type: "attack", amount: 5, hits: 2, label: "多層纏繞" },
    ],
  },
  templecorpse: {
    id: "templecorpse",
    name: "污染底泥",
    artKey: "templecorpse",
    hp: 54,
    moves: [
      { type: "attack", amount: 10, label: "毒泥覆蓋" },
      { type: "block", amount: 10, label: "淤泥防護" },
      { type: "curse", amount: 1, label: "重金屬滲入" },
    ],
  },
  macaque: {
    id: "macaque",
    name: "入侵獅子魚",
    artKey: "macaque",
    hp: 52,
    moves: [
      { type: "attack", amount: 4, hits: 3, label: "毒棘連刺" },
      { type: "buff", amount: 2, label: "快速繁殖" },
      { type: "attack", amount: 10, label: "掠食衝擊" },
    ],
  },
  warlock: {
    id: "warlock",
    name: "盜獵快艇",
    artKey: "warlock",
    hp: 68,
    elite: true,
    moves: [
      { type: "attack", amount: 12, label: "非法撈捕" },
      { type: "buff", amount: 3, label: "引擎加速" },
      { type: "curse", amount: 2, label: "廢油排放" },
    ],
  },
  foxshade: {
    id: "foxshade",
    name: "偽裝漁船",
    artKey: "foxshade",
    hp: 72,
    elite: true,
    moves: [
      { type: "attack", amount: 8, hits: 2, label: "非法拖網" },
      { type: "debuff", amount: 3, label: "煙霧掩護" },
      { type: "blockAttack", amount: 7, block: 10, label: "偽裝反擊" },
    ],
  },
  tigerlord: {
    id: "tigerlord",
    name: "非法捕鯨母船",
    artKey: "tigerlord",
    hp: 118,
    boss: true,
    moves: [
      { type: "attack", amount: 16, label: "主砲轟擊" },
      { type: "attack", amount: 6, hits: 3, label: "魚叉連射" },
      { type: "buff", amount: 3, label: "全速運作" },
      { type: "blockAttack", amount: 10, block: 12, label: "鋼鐵船體" },
    ],
  },
};

export const NODE_DEFS: Record<NodeType, { name: string; desc: string }> = {
  combat: { name: "海域巡查", desc: "遭遇污染源或入侵物種。驅離後獲得補給與新技能。" },
  elite: { name: "非法作業現場", desc: "更危險的威脅正在破壞海洋。擊退後必得遺物。" },
  event: { name: "海上見聞", desc: "巡邏途中遇見意外，每個選擇都有代價。" },
  rest: { name: "中心補給站", desc: "回到嘉義縣海洋教育中心補給，療傷或強化裝備。" },
  shop: { name: "漁港裝備鋪", desc: "花補給費購買技能、遺物，或請店主報廢舊裝備。" },
  boss: { name: "外海決戰", desc: "非法捕鯨母船盤踞在布袋外海，這是最後的任務。" },
};

export const EVENTS: EventDef[] = [
  {
    id: "well",
    title: "擱淺海龜",
    body: "沙灘上一隻綠蠵龜被廢棄漁線緊緊纏住，牠的眼睛仍然清澈，像在等待什麼。",
    choices: [
      { id: "wellHeal", title: "花時間救援", desc: "耐心剪除漁線，送牠回海。回復 12 點生命。" },
      { id: "wellRelic", title: "採樣後通報", desc: "記錄傷勢並呼叫救援隊。失去 7 點生命，獲得 1 件遺物。" },
    ],
  },
  {
    id: "fox",
    title: "神秘老漁翁",
    body: "一位老漁翁坐在防波堤上，手裡握著一張泛黃的手繪海圖，沉默地遞向你。",
    choices: [
      { id: "foxCard", title: "接過海圖", desc: "舊海圖記錄著秘密航道。獲得 1 張隨機技能牌。" },
      { id: "foxRemove", title: "付錢換情報", desc: "花費 40 補給費，移除 1 張多餘的裝備牌。" },
    ],
  },
  {
    id: "temple",
    title: "廢棄燈塔",
    body: "燈塔裡有人留下一批補給品和一本工具手冊，燈塔本身已多年無人維護。",
    choices: [
      { id: "templeUpgrade", title: "修復燈塔", desc: "邊修邊學，將 1 張牌升級強化。" },
      { id: "templeGold", title: "取走補給", desc: "快速取走物資，但來不及處理堆積的污泥。獲得 80 補給費，將 1 張污泥加入牌組。" },
    ],
  },
  {
    id: "scholar",
    title: "研究員的筆記",
    body: "海洋教育中心的研究員留下一本調查筆記，記錄著這片海域的物種與污染數據，字跡潦草卻充滿細節。",
    choices: [
      { id: "scholarCopy", title: "仔細研讀", desc: "從中習得一項技巧，但調查耗時讓污染蔓延。複製 1 張非基礎牌，並加入 1 張污泥。" },
      { id: "scholarLeave", title: "繼續前進", desc: "任務優先，筆記留給下一位志工。什麼也不發生。" },
    ],
  },
];
